apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: btcwallet-pv-claim #skip this on domido cluster
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi
