apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: btcwallet
  labels:
    name: btcwallet
spec:
  replicas: 1 # need 2 or more
  template:
    metadata:
      labels:
        name: btcwallet
    spec:
      containers:
      - name: btcwallet
        image: OpenBazaar/bitcoin-wallet
        imagePullPolicy: Always
        ports:
        - name: btcwalletport
          containerPort: 8234 #SERVICEPORT
        volumeMounts:
        - name: btcwalletdb
          mountPath: /root/.spvwallet
          subPath: spwallet
        env:
        - name: GRPCPORT
          value: "8234"
      imagePullSecrets:
       - name: regsecret
      volumes:
      - name: btcwalletdb
        persistentVolumeClaim:
          claimName: btcwallet-pv-claim

