apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bitcoinwallet
  labels:
    name: bitcoinwallet
spec:
  replicas: 1 # need 2 or more
  template:
    metadata:
      labels:
        name: bitcoinwallet
    spec:
      containers:
      - name: bitcoinwallet
        image: opendomido/bitcoinwallet
        imagePullPolicy: Always
        ports:
        - name: btcwalletport
          containerPort: 8234 #SERVICEPORT
        volumeMounts:
        - name: btcwalletdb
          mountPath: /root/.spvwallet
          subPath:
        #env:
      imagePullSecrets:
       - name: regsecret
      volumes:
      - name: btcwalletdb
        persistentVolumeClaim:
          claimName: btcwallet-pv-claim       