apiVersion: v1
kind: Service
metadata:
  name: btcwallet
  labels:
    name: btcwallet
spec:
  # type: ClusterIP
  ports:
  - name: btcwalletport
    port: 8234
    targetPort: 8234
  selector:
    name: btcwallet
